name: Sync Mihomo Rules to Loon Plugin

on:
  push:
    paths:
      - 'rule.list' # 只有当 rule.list 文件有变化时才触发
    branches:
      - main # 或者你的主分支名称，比如 master

jobs:
  sync:
    runs-on: ubuntu-latest # 在 Ubuntu 虚拟机上运行

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # 检查你的仓库代码

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 使用最新的 Python 3 版本

    - name: Run sync script
      run: python sync_rules.py # 运行你刚刚创建的 Python 脚本

    - name: Commit and push changes
      run: |
        git config user.name 'github-actions[bot]' # 配置 Git 用户名
        git config user.email 'github-actions[bot]@users.noreply.github.com' # 配置 Git 用户邮箱
        git add resource/loon/rule.plugin # 添加修改后的 plugin 文件
        git commit -m "chore: Sync rule.list to rule.plugin [skip ci]" || echo "No changes to commit" # 提交更改，并跳过再次触发 CI
        git push # 推送更改
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub 提供的自动认证 token